vocab = {
    "ständig an allem herummeckern müssen": "to gripe, complain",
    "nörgeln": "synonym of herummeckern",
    "stolpern": "stumble",
    "die nächtlichen Auftritte": "nightly performances",
    "der Clou an der Sache": "the point of the whole thing",
    "unterhaltsam": "entertaining",
    "suhlen": "wallow",
    "dahergelaufenes Mehrkornbrot mit seinen zehn Getreidesorten": "random multigrain bread with its ten types of grain",
    "das Mehl, die Mehle": "flour",
    "die Himmelsrichtung, die Himmelsrichtungen": "direction (compass)",
    "der Ausbau, die Ausbauten": "expansion",
    "um den Rückstand gegenüber dem Westen auszugleichen": "to close the gap with",
    "wahrnehmen": "perceive",
    "die Verkehrsmittel, die Verkehrsmittel": "means of transportation",
    "die Einrichtungen, die Einrichtungen": "facilities",
    "benachteiligen": "to disadvantage",
    "sich beschweren": "complain",
    "unzureichend": "insufficient",
    "vorläufig": "provisional",
    "das Gehalt, die Gehälter": "salary",
    "die Auflage, die Auflagen": "conditions, restrictions",
    "ermitteln": "to investigate",
    "schunkeln": "sway",
    "das Dreigestirn, die Dreigestirne": "triumvirate",
    "das Gelände, die Gelände": "compound, complex",
    "die Tagung, die Tagungen": "conference",
    "die Kundgebung, die Kundgebungen": "rally",
    "der Insasse, die Insassen": "occupant (of vehicle), inmate, passenger",
    "die Urkunde, die Urkunden": "certificate",
    "genehmigen": "approve, permit, authorize",
    "die Klage, die Klagen": "lawsuit",
    "verklagen": "to sue",
    "der Rechtsanwalt, die Rechtsanwälte": "lawyer",
    "jdn./etw. zurückweisen": "reject",
    "die Hinrichtung, die Hinrichtungen": "execution",
    "geständiger Mörder": "confessed murderer",
    "geistig beeinträchtigt": "mentally impaired",
    "beeinträchtigen": "to impair, to compromise, to tarnish, to mar, to prejudice",
    "die Schwangerschaft, die Schwangerschaften": "pregnancy",
    "ausgehen von": "to take as one's starting point",
    "der Darm, die Därme": "intestines",
    "jucken": "to itch",
    "verdrängen": "to supersede, to suppress, to displace",
    "der Ballaststoff, die Ballaststoffe": "dietary fiber",
    "auf etw. setzen": "to bet on, fig. to focus",
    "billigen": "to approve, condone",
    "der Ertrag, die Erträge": "yield, harvest",
    "der Kunstdünger, die Kunstdünger": "fertilizer",
    "aufwendig": "elaborate, lavish",
    "die Liegenschaft, die Liegenschaften": "real estate, properties",
    "vermeintlich": "alleged",
    "die Luftfahrtmesse, die Luftfahrtmessen": "aviation trade fair",
    "beläuft sich": "amounts to (x dollars, Euros, etc.)",
    "Mittelstrecken-": "in compounds, medium-range",
    "langfristig": "long-term",
    "versteigern": "to auction",
    "eine Auszeichnung vergeben": "to award a prize",
    "der Sattelzug, die Sattelzüge": "tractor trailer",
    "dann eben nicht": "fine then",
    "der Netzschalter, die Netzschalter": "power switch",
    "das Scharnier, die Scharniere": "hinge",
    "der Bügel, die Bügel": "clothes hanger, arm of glasses",
    "beschleunigen": "to accelerate",
    "ein schwarzes Loch": "black hole",
    "Ist er noch im Unternehmen tätig?": "Is he still with the company?",
    "Das Gericht scheint ein Schüssel mit Suppe oder Eintopf zu sein": "the dish appears to be a bowl of soup or a stew",
    "sich versprechen": "to expect",
    "nachhaltiges Wachstum": "sustainable development"
}
